### ISSUE TITLE
Unify Custom and Non-Custom Field Access

### ISSUE THREAD

**Issue by ChrisGrohHS** [Parature/ParatureSDK#1]
Provide a unified way of accessing custom and non-custom fields. For example:

Ticket["Assigned_To"] = new Csr();// Set built-in field
Ticket["213"] = "Custom Field";// Set custom field

Ticket.Assigned_To = new Csr();// Wrapper for performing Ticket["Assigned_To"] = new Csr();

**Comment by brtubb** [comment]
Definitely going to move to something close to this. Right now, the base class for entities is a mess and doesn't address Static Fields at all - that's left to each derived class to deal with. This is obviously a poor methodology but sadly well ingrained in the codebase.

We are currently moving towards a better solution:
* Adding classes: Field (base class), StaticField, CustomField (modified)
* Base Entity Class (ModuleWithCustomFields) will have a publicly accessible list of fields
* Derived classes (Ticket, Account, etc) will use property getters and setters for each Static field

This is WIP internally, but there is some discussion on the handling of Field values that has us hung temporarily. Specifically, field values are stored as a string(!) internally, so there is a lot of bad parsing and an incompatibility with complex objects. Likely, we'll move to something similar to [what Dynamics CRM does](http://msdn.microsoft.com/en-us/library/gg326129.aspx) with Entity.GetAttributeValue<T>() so we can use complex types. 

We have a lot of cleanup going on internally, which we'll make publicly available when we reach usable states. Due to the large amount of shuffling going on, we're keeping it close to our chest, but once the dust settles we'll move to more open development.

**Comment by brtubb** [comment]
Indexers are now available in the Release_V2 branch. it works slightly different than the original suggestion, for a variety of reasons.

1. Static fields are referenced by their schema name (string)
Ticket["Assigned_To"]
2. Custom fields are referenced by their integer id
Ticket[213]
--> We aren't directly supporting custom field retrieval using the schema name via indexers, as there are other methods that provide this functionality, and it isn't recommended anyways (particularly as we move towards better localization support)
3. Indexer retrieval will retrieve a StaticField or CustomField object, both extending the base Field class. All custom field values are represented as strings or lists of objects, while Static Fields are actual objects with their own typecasting retrieval necessary (Ticket["Assigned_To"].GetValue<Csr>()).
