### ISSUE TITLE
System.Web.HttpUtility.UrlEncode cannot be used from a partially trusted caller

### ISSUE THREAD

**Issue by philmoz** [Parature/ParatureSDK#18]
I'm building a plugin for Dynamics CRM 2015 Online to push updates to Parature.

The ParaQuery.ProcessEncoding method uses the System.Web.HttpUtility.UrlEncode method - this cannot be called from a CRM sandboxed plugin (throws 'That assembly does not allow partially trusted callers' exception).

The System.Net.WebUtility.UrlEncode method appears to works correctly and removes then need to include System.Web in the ParatureSDK project.

**Comment by brtubb** [comment]
We'll take a look in changing to this separate library. Are they functionally equivalent?

**Comment by brtubb** [comment]
So there is a difference in the two methods.
http://www.samnoble.co.uk/2014/05/21/beware-webutility-urlencode-vs-httputility-urlencode/
Primarily, WebUtility encodes with upper case hex, while HttpUtility encodes lower case.

We'll need to debate internally before we move to the WebUtility method, as it may cause unforeseen consequences.

@philmoz Have you continued to have success with the UrlEncode method?

**Comment by philmoz** [comment]
I am using System.Net.WebUtility.UrlEncode in my CRM plugin - so far it does not seem to have caused any problems.

**Comment by brtubb** [comment]
Investigating... Our current project uses .NET4.0 and System.Net.WebUtility.UrlEncode is 4.5+. Looking into alternatives. I'm not sure we want to move to 4.5 quite yet.

**Comment by brtubb** [comment]
In short and for historical purposes, we should be using some form of HttpUtility.UrlEncode.

Even better lay of the UrlEncoding land:
http://blogs.msdn.com/b/yangxind/archive/2006/11/09/don-t-use-net-system-uri-unescapedatastring-in-url-decoding.aspx

Encoding:
![image](https://cloud.githubusercontent.com/assets/10502971/8555533/b039cc34-24be-11e5-82bb-0722df2039eb.png)

Decoding:
![image](https://cloud.githubusercontent.com/assets/10502971/8555542/bee64c6c-24be-11e5-89bf-28b053035b5b.png)

From testing and research, the biggest difference across .NET methods will be handling spaces as either a + or %20. Looking at recommendations on [StackOverflow](http://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20) and the actual [Parature documentation](https://support.parature.com/public/doc/api.html#article-list) on the matter, we should be using '+' for URL encoding instead of '%20'.

**Comment by philmoz** [comment]
I have to use .Net 4.5.2 (CRM 2015 plugin requirement), so far I haven't had any problems from the version change.

**Comment by brtubb** [comment]
@philmoz 
We met internally and plan on updating to .Net 4.5, not 4.5.2. Would this block a CRM 2015 plugin from running?

**Comment by philmoz** [comment]
The current CRM 2015 SDK requires .Net 4.5.2. I have to build from source anyway as I can't upload an external library .DLL to CRM online. My plugin .DLL has to be self contained.

**Comment by brtubb** [comment]
@philmoz Thanks for the explanation. We'll settle on 4.5 for now, since you'll be pulling in the project anyways. That way we can be compatible from a namespace perspective, while maximizing compatibility with other projects.

**Comment by brtubb** [comment]
This is now reflected in the master branch. Please let us know if you end up using the latest version and have issues. Thank you very much for the logged Issues.
