### ISSUE TITLE
Use Namespaces instead of Nested Classes

### ISSUE THREAD

**Issue by ChrisGrohHS** [Parature/ParatureSDK#2]
Use namespaces instead of nested classes.

**Comment by brtubb** [comment]
Thanks for the suggestion!

We are currently working on a bunch of fixes in a separate (internal) branch. Nested classes will be entirely replaced with folders. Classes under these namespaces will have their own files rather than everything being embedded in the "namespace class". Naming conventions are being heavily reworked to fit the [C# Coding Conventions](http://msdn.microsoft.com/en-us/library/ff926074.aspx) as well.

There will be minor API breakage with these changes as well:
* Method names will be modified
* Base classes renamed
* Namespaces will be close to the same, but there will be some inconsistencies
 * You'll have to use _ParatureAPI.ParaObjects.Account_ instead of just _ParaObjects.Account_
 * Static methods originally under the "namespace classes" will be in a new utils class in that namespace

**Comment by brtubb** [comment]
This is done in in the latest release branch. The new namespace for the binary is ParatureSDK, so there is a small change from my previous comment.
