### ISSUE TITLE
Exception Handling for Apihandler

### ISSUE THREAD

**Issue by AdamHong** [Parature/ParatureSDK#3]
Frequently finding myself doing things like this:

var response = Apihandler.DoStuff();
if( response.HasException ) {
  //log message
}

We can find a better way to do this. Some way to specify a callback and optional message to allow different logging methods.

**Comment by brtubb** [comment]
We should at least leave it as optional. It's a bit better than
```
try{
   ApiHandler.DoStuff();
} catch(Exception e) {
   //let's pretend we'll log this in the future
}
```
I could see this being helpful with tight loops doing the same thing over and over, in an attempt to limit code stink. Something like:
```
ApiHandler.OnException(() => {
   //log
   continue;
});

for(var i = 0; i < 1000; i++) {
   var accountId = i; 
   var Account = ApiHandler.GetAccount(accountId);

   //exceptions would happen since it'd be empty or null, but we want the loop to continue
   Account.DoMoreStuff(); 
}
```
Not sure if the continue would even work there, and not particularly impressed with how it looks. Wouldn't throwing an Exception be a more ideal method to get what you are aiming for?

**Comment by brtubb** [comment]
I'm starting to like syntax like so:

'''
ApiHandler.Ticket.GetList(credentials, 
  onFail: (apiResponse) => {
     //handle failure
  });
'''

What do you suggest doing after the onFail callback though? Won't you still have to check the returned message?

Tempted to close this, since I don't think the code stink is too massive with the if-then. Can always extract to a method as necessary, which would happen anyways when there's a lot to do in the failure scenario.

I definitely see a point to being able to specify a global error handler (for logging or otherwise). This coincides with a possible shift to a "Service" object rather than passing the credentials around on each call. Thoughts?

**Comment by brtubb** [comment]
@AdamHong, an option would be adding a global PostRequest handler, similar to what we do before requests (see the ApiRequestSettings.GlobalPreRequest delegate).
