### ISSUE TITLE
Needs verification | Default setting of "Email Notification" field on new ticket creation

### ISSUE THREAD

**Issue by paulfischer** [Parature/ParatureSDK#4]
Hi Team - 

Can you please investigate a potential bug in creating a new ticket through the SDK? We had couple reports that if you do not set "email notification" when creating a new ticket, its default value is set to "Do Not Email Notifications about this Ticket" - which can be pretty detrimental to most use cases. I'd anticipate a default value mirroring the service desk of "Use customer email notification preferences".

Thanks!

**Comment by brtubb** [comment]
WIP, issue found and understood. We'll do a delta release when tested.

**Comment by nbuckel** [comment]
Not sure if its related, but I've found that updating a ticket where Email notification is set to use customer preferences will overwrite that to be Always email. I think this could be an API issue rather than an SDK one as it looks like that field is a boolean in the API which it's not in the front end.

**Comment by brtubb** [comment]
Nick, you mean that there is a discrepancy between the Service Desk (UI) and the API's boolean value? Warrants further testing, thanks for bringing up this test case.

To address Paul's initial issue report - the code was using "bool" rather than "bool?" for the Email_Notification property. This defaulted to the value of "false" rather than "null" when generating the XML. This is fixed in our codebase and should be pushed shortly after more testing. The update scenario brought up by nbuckel isn't tested yet and will be investigated. I'm guessing updating a ticket without the "Email_Notification" node in the XML may default to the customer's preference.

**Comment by nbuckel** [comment]
Yeah - the UI has 3 options but the API is showing as a bool. The API is returning true if the UI says Customer Preferences or Always notify.

**Comment by brtubb** [comment]
We are using a bool? now, so I believe it shouldn't be happening anymore. Nbuckel, if you do see this happening still in the newest release on GitHub or Nuget please let us know. I haven't tested conclusively so will leave this open for now.

**Comment by nbuckel** [comment]
Hi @brtubb 

The api schema still shows a bool:

``` xml
<Email_Notification display-name="Email Notification" required="false" editable="true" field-type="checkbox" data-type="boolean"/>
<Email_Notification_Additional_Contact display-name="Email Notification For Additional Contact" required="false" editable="true" field-type="checkbox" data-type="boolean"/>
```

Nick

**Comment by brtubb** [comment]
Oh I see what you mean. The SDK is using a Nullable<Boolean>. When it is null, it doesn't send the Email_Notification XML node at all back to the server. Previously it would send "false" when it should be null. This *should* leave the ticket setting alone now, despite the API's schema only having true/false as the settings.

Please note that this has not been exhaustively tested yet, but I have not seen the ticket Email notification settings change anymore with the latest versions.

**Comment by brtubb** [comment]
@nbuckel 

Ok, total disconnect on my side. Definitely an API issue, not a problem with the SDK. Closing here, but escalating to an API defect to see if this can be fixed. I agree that this should default to "Use customer default"
