### ISSUE TITLE
XML Deserialization error when call ArticleFolder's schema method

### ISSUE THREAD

**Issue by dwcai** [Parature/ParatureSDK#9]
When making a call to ArticleFolder's schema method, I am getting the following error message: 
```
System.InvalidOperationException: There is an error in XML document (0, 0).
  Stack Trace: 
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at ParatureSDK.XmlToObjectParser.ParaEntityParser.EntityFill[T](XmlDocument xmlDoc)
   at ParatureSDK.ApiHandler.Article.ArticleFolder.Schema(ParaCredentials ParaCredentials) 

System.FormatException: The string '' is not a valid Boolean value.
  Stack Trace: 
   at System.Xml.XmlConvert.ToBoolean(String s)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderArticleFolder.Read1_NullableOfBoolean(Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderArticleFolder.Read5_ArticleFolder(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderArticleFolder.Read6_ArticleFolder() 
```
This can be fixed by updating the following code:
```C#
ArticleFolder = ParaEntityParser.EntityFill<ParaObjects.ArticleFolder>(ar.XmlReceived);
```
to
```C#
var purgedSchema = ApiUtils.RemoveStaticFieldsNodes(ar.XmlReceived);
ArticleFolder = ParaEntityParser.EntityFill<ParaObjects.ArticleFolder>(purgedSchema);
```

An alternative option would be to remove the Schema method, as I don't suppose there are any custom fields for this entity anyway. 

Thanks!

**Comment by dwcai** [comment]
Same should done for the following entities: 
* CsrStatus
* CustomerStatus
* TicketStatus

**Comment by dwcai** [comment]
Same should done for the following entities: 
* CsrStatus
* CustomerStatus
* TicketStatus

**Comment by brtubb** [comment]
Thanks for the catch on the ArticleFolder! Will be fixed in the next release. Going to leave for now - will reevaluate when we go through the non-business entities with a fine-toothed comb. I've found some duplicate entities under the ApiHandler namespace (Csr.CsrStatus and Entities.CsrStatus, for example), so this needs to be cleaned up.

I don't see schema calls for the CsrStatus, CustomerStatus, or TicketStatus classes. Are they under the ApiHandler.Entities folder or subclasses of the business classes (in Csr.cs, Account.cs, etc)?

**Comment by dwcai** [comment]
Schema call for CsrStatus is under ApiHandler.Csr class, and CustomerStatus is under ApiHandler.Entities, so is TicketStatus (under ApiHandler.Entities). 

Thanks for looking into this!

**Comment by dwcai** [comment]
My apologies, the issue with CsrStatus and CustomerStatus is a totally different one, since they do not have a Schema method. The problem happens when reading data from Parature. I have two problems here. 
* When reading data for CsrStatus, CsrStatusGetList method will fail, since the root node of the XML document returned from Parature is "entities" while ParaEntityList<ParaObjects.CsrStatus> serializer expects an "Entities" root node. 
* I tried to change the root node's name to "Entities", I am getting another problem, the individual record can not be serialized to CsrStatus, since the node is "Status", not "CsrStatus". 

Sorry again for the confusion.

**Comment by brtubb** [comment]
Fixed the ArticleFolder issue (schema call removed), but haven't gotten to the latest issue you pointed out. First, thanks for clarifying! It'll be in the next push.

**Comment by brtubb** [comment]
The lower case "entities" in the schema is a bug, but we've added a temporary workaround while we report and push for a fix. You'll now be able to retrieve the status for Csrs, Customers, and Tickets in 2.0.4+ (NuGet) and the master branch.

Also removed the schema calls to these entities, since they shouldn't be necessary (no custom fields).
